const Images = {
    img1 : require('./logo.png'),
    img2 : require('./cro1.jpeg'),
    img3 : require('./cro2.jpeg'),
    img4 : require('./cro3.jpeg'),
    img5 : require('./cro4.jpeg'),
    img6 : require('./About.gif'),
    ser1 : require('./services-1.jpg'),
    ser2 : require('./services-2.jpg'),
    ser3 : require('./services-3.jpg'),
    ser4 : require('./services-4.jpg'),
    ser5 : require('./services-5.jpg'),
    obc  : require('./carousle-obc.gif'),
    aog : require('./aog.jpg'),
    auto : require('./auto.jpg'),
    fashion : require('./fashion.jpg'),
    aviations : require('./aviations.jpg'),
    freight : require('./freight.jpg'),
    healthcare : require('./healthcare.jpg'),
    marine : require('./marine.jpg'),
    oil : require('./oil.jpg'),
    media : require('./media.jpg'),
    mining : require('./mining.jpg'),
    ship : require('./ship.jpg'),
    telecom : require('./telecom.jpg'),
    hitech : require('./hitech.jpg'),
}

export default Images;